In [1]:
# NRO 12
# 12-GMM.ipynb
%load_ext autoreload
%autoreload 2

In [20]:
from sklearn.mixture import GaussianMixture

In [22]:
import pandas as pd
df = pd.read_csv('alturas-pesos-1-train.csv')

In [11]:
print(df[['Altura', 'Peso']])

      Altura  Peso
0        162    61
1        181    97
2        172    73
3        157    55
4        151    56
...      ...   ...
7995     160    62
7996     177    83
7997     170    75
7998     166    65
7999     171    80

[8000 rows x 2 columns]


In [12]:
pesos_alturas = df[['Peso', 'Altura']].values

In [17]:
print(pesos_alturas)

[[ 61 162]
 [ 97 181]
 [ 73 172]
 ...
 [ 75 170]
 [ 65 166]
 [ 80 171]]


In [21]:
# One can think of mixture models as generalizing k-means clustering to incorporate information about the covariance structure of the data as well as the centers of the latent Gaussians

# GaussianMixture have options to constrain the covariance of the difference classes estimated
# spherical, diagonal, tied or full covariance #@TODO what is the diferents between this modes or types
# interesante: https://towardsdatascience.com/gaussian-mixture-models-explained-6986aaf5a95
# numero de componentes = cantidad de clusters
# cuantos componentes? cuando es mejor a N cantidad de cluster? silhouette? @TODO preguntar alternativo?
# en este ejemplo colocaron dos porque recordemos que al ver el histograma tenia dos gausianas.
# una gaussiana para mujeres y otra para hombres.
# tol = La tolerancia? https://scikit-learn.org/stable/modules/generated/sklearn.mixture.GaussianMixture.html
# random_state= semilla para garantizar la reproducibilidad de los resultados.

# model = estimated Gaussian mixture models
model = GaussianMixture(n_components=2, covariance_type='full', init_params='kmeans', max_iter=10000, tol=0.0001)

In [24]:
model.fit(pesos_alturas)

GaussianMixture(max_iter=10000, n_components=2, tol=0.0001)

In [25]:
model.means_

array([[ 60.65461028, 160.73175005],
       [ 84.01749406, 174.54179157]])

In [30]:
model.covariances_

array([[[75.22233469, 49.79701663],
        [49.79701663, 46.86474106]],

       [[79.83813643, 54.6210906 ],
        [54.6210906 , 51.28423416]]])

In [ ]:
# notebook
# 13 test gauss.ipynb

In [1]:
%matplotlib inline
from ipywidgets import interactive, fixed, interact, widgets
from matplotlib import pyplot as plt
from IPython.display import display, Markdown
from helper import plot_mv_gaussian
import numpy as np

In [2]:
display(Markdown('$x^2$'))

$x^2$

In [3]:
def plot_gauss(sigma_x1=1, sigma_x2=1, corr_coef=0.0):
    sigma_x1x2 = corr_coef*sigma_x1*sigma_x2
    corr_mat = np.array([[sigma_x1,sigma_x1x2],[sigma_x1x2,sigma_x2]])
    plot_mv_gaussian(np.array([0, 0]), corr_mat, initview=(35, -45),
                     N=50, autoscale=([-2, 2], [-2, 2], [0, 0.15]))
    print(corr_mat)
    plt.show()
    return

In [ ]:
w=interactive(plot_gauss, sigma_x1=(0.5,4), sigma_x2=(0.5,4), corr_coef=(-0.9, 0.9))
w

interactive(children=(FloatSlider(value=1.0, description='sigma_x1', max=4.0, min=0.5), FloatSlider(value=1.0,…

In [8]:

a = widgets.FloatSlider(1.0, min=0.5, max=4, description='$\sigma_{x_1}^2$')
b = widgets.FloatSlider(1.0, min=0.5, max=4, description='$\sigma_{x_2}^2$')
c = widgets.FloatSlider(0, min=-0.9, max=0.9, description='$ro$')
ui = widgets.HBox([a, b, c])
out = widgets.interactive_output(plot_gauss, {'sigma_x1': a, 'sigma_x2': b, 'corr_coef': c})
display(ui, out)

Output()

In [2]:
import numpy as np
datos = np.random.choice([0,1], 500, p=[0.3, 0.7])
print(datos)

[1 1 1 1 1 0 1 0 0 1 1 1 0 1 1 1 1 0 0 1 0 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1
 0 1 0 0 0 1 1 1 1 1 1 1 1 0 0 1 1 0 1 1 1 0 1 1 0 1 0 1 0 1 1 1 0 1 1 0 1
 1 0 1 1 1 1 1 0 1 0 1 1 0 1 1 1 1 1 1 1 1 1 0 1 1 1 1 0 1 1 1 0 1 0 1 1 1
 0 1 1 1 1 1 1 1 1 1 1 0 0 1 0 1 1 1 1 1 1 0 1 0 1 1 0 0 1 0 0 0 1 1 1 0 0
 1 1 1 0 0 1 0 1 0 1 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 0 1 1 1 1 1 1 0 1 1 0 1
 0 0 0 1 1 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 0 1 1 0 0 1 1 1 1 1 1 1 0 1 1
 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 0 0 0 1 1 0 1 1 0 1 1 0 0 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1
 1 1 1 1 1 0 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 0 0 1 1 0 0 1 0 0 1 1 0 1 0 1
 1 1 0 1 1 0 1 1 1 0 1 0 1 0 1 1 0 1 0 1 1 1 0 1 0 1 1 0 1 1 1 1 1 1 1 1 1
 1 0 1 1 1 0 1 1 1 1 1 1 1 0 0 0 1 1 1 0 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1
 1 1 1 0 0 0 1 0 1 1 0 1 1 1 1 0 0 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 0 1 1 1 1 1 0 1 1 0 0 1 0 1 0 1 0 1 0 1 1 1 0 0 1 1 0 0 0 1 0 1
 0 0 0 1 1 0 1 1 1 1 1 1 

In [3]:
np.mean(datos)

0.714